// LOGIN REQUESTS
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILED = 'LOGIN_REQUEST_FAILED';

// FETCH USERS

export const FETCH_USERS = 'FETCH_USERS'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED'

// LOGOUT REQUEST
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

// PERSONAL CHAT
export const PERSONAL_CHAT_REQUEST = 'PERSONAL_CHAT_REQUEST';
export const PERSONAL_CHAT_SUCCESS = 'PERSONAL_CHAT_SUCCESS'
export const PERSONAL_CHAT_FAILED = 'PERSONAL_CHAT_FAILED'

// SEND MESSAGE IN PERSONAL

export const PERSONAL_CHAT_MESSAGE_REQUEST = 'PERSONAL_CHAT_MESSAGE_REQUEST';
export const PERSONAL_CHAT_MESSAGE_SUCCESS = 'PERSONAL_CHAT_MESSAGE_SUCCESS'
export const PERSONAL_CHAT_MESSAGE_FAILED = 'PERSONAL_CHAT_MESSAGE_FAILED'

// GET MESSAGE HISTORY

export const GET_MESSAGE_HISTORY = 'GET_MESSAGE_HISTORY'